accelerator: gpu
batch_size: 32
check_val_every_n_epochs: 20
ckpt_every_n_epochs: 20
datamodule: celeba
devices: 1
lr: 1e-5
lr_scheduler: cosine
max_epochs: 60
metrics: [loss, acc, acc_by_class, acc_by_group, global_cov, inter_class_cov, intra_class_cov, inter_group_cov, intra_group_cov, class_trace, group_trace]
model: resnet
resnet_version: 18
wandb: True
num_sanity_val_steps: 0
optimizer: adamw
