accelerator: gpu
batch_size: 32
check_val_every_n_epochs: 2
ckpt_every_n_epochs: 20
datamodule: celeba
devices: 1
lr: 1e-5
lr_scheduler: cosine
max_epochs: 200
metrics: [loss, acc, acc_by_class, acc_by_group, cosine_similarity, directional_error]
model: resnet
resnet_version: 50
num_sanity_val_steps: 0
optimizer: adamw
wandb: True