accelerator: gpu
batch_size: 32
check_val_every_n_epochs: 2
ckpt_every_n_epochs: 20
datamodule: civilcomments
devices: 1
lr: 1e-5
lr_scheduler: linear
max_epochs: 200
metrics: [loss, acc, acc_by_class, acc_by_group, cosine_similarity, directional_error]
model: bert
bert_version: tiny
num_sanity_val_steps: 0
optimizer: adamw
wandb: True